flowchart TD
START([START]) -->
AssignTotals["TotalSales = 0<br/>TotalCommission = 0"] -->
ReadN["Read Representative Number (N)"] -->
CheckEnd{N == 555}
  CheckEnd -- True -->
    PrintTotals["Print TotalSales<br/>and TotalCommission"] -->
    End(["End"])
  CheckEnd -- False -->
    ReadData["Read Name (M) and Sales Amount (A)"] -->
    CheckAmount{A < 50,000}
      CheckAmount -- True -->
        CalcLow[Commission = A * 0.025] -->
        PrintData[/Print N, M, A, Commission/] -->
        UpdateTotals[TotalSales += A<br/>TotalCommission += Commission] -->
        ReadNext[/"Read Next Representative Number (N)"/] -->
        CheckEnd
      CheckAmount -- False -->
        CalcHigh[Commission = A * 0.055] -->
        PrintData
