[[language]]
name = "typescript"
auto-format = false
language-servers = [
  "biome",
  { name = "typescript-language-server", except-features = [
    "format",
  ] },
]

[[language]]
name = "javascript"
auto-format = false
language-servers = [
  "biome",
  { name = "typescript-language-server", except-features = [
    "format",
  ] },
]
